# Generated by Django 4.2.13 on 2024-06-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Seekers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('skills', models.JSONField()),
                ('experience', models.IntegerField(null=True)),
                ('education', models.JSONField()),
                ('contact', models.IntegerField()),
                ('expected_salary', models.CharField(max_length=10, null=True)),
                ('notice_period', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('experience', models.IntegerField(null=True)),
                ('key_skills', models.JSONField()),
                ('education', models.JSONField()),
                ('employment_type', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('locations', models.JSONField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('profile_summary', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('applications_count', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='CareerHub.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='applications/')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerHub.jobdetails')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerHub.job_seekers')),
            ],
        ),
    ]
