# Generated by Django 4.2.13 on 2024-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='Company',
            field=models.CharField(default='TCS', max_length=200),
            preserve_default=False,
        ),
    ]
